package DinoText_GUI.VIEW;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DinoViewer_View extends JFrame {
    private JTextField JTextField_Input;
    private JPanel panel1;
    private JLabel JLabel_Filename;
    private JTextPane JTextPane_Output;

    public DinoViewer_View() {
        this.setContentPane(panel1);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(600, 580);
        this.setVisible(true);
    }

    // getters
    public String getJtextField_Input() {
        return JTextField_Input.getText();
    }

    public String getJLabel_Filename() {
        return JLabel_Filename.getText();
    }

    public String getJTextPane_Output() {
        return JTextPane_Output.getText();
    }

    // setters
    public void setJTextField_Input(String input) {
        JTextField_Input.setText(input);
    }

    public void setJLabel_Filename(String input) {
        JLabel_Filename.setText(input);
    }

    public void setJTextPane_Output(String output) {
        JTextPane_Output.setText(output);
    }

    // action Listener

    public void addListener_JTextField_Input(ActionListener listenForJTextField_input) {
        JTextField_Input.addActionListener(listenForJTextField_input);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        JTextField_Input = new JTextField();
        panel1.add(JTextField_Input, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        JLabel_Filename = new JLabel();
        JLabel_Filename.setText("Label");
        panel1.add(JLabel_Filename, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        JTextPane_Output = new JTextPane();
        JTextPane_Output.setText("");
        scrollPane1.setViewportView(JTextPane_Output);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
