/******************************************************************************************************************
 *      ███        ▄████████    ▄████████     ███             ▄███████▄    ▄████████ ███▄▄▄▄      ▄████████  ▄█
 * ▀█████████▄   ███    ███   ███    ███ ▀█████████▄        ███    ███   ███    ███ ███▀▀▀██▄   ███    ███ ███
 *    ▀███▀▀██   ███    █▀    ███    █▀     ▀███▀▀██        ███    ███   ███    ███ ███   ███   ███    █▀  ███
 *     ███   ▀  ▄███▄▄▄       ███            ███   ▀        ███    ███   ███    ███ ███   ███  ▄███▄▄▄     ███
 *     ███     ▀▀███▀▀▀     ▀███████████     ███          ▀█████████▀  ▀███████████ ███   ███ ▀▀███▀▀▀     ███
 *     ███       ███    █▄           ███     ███            ███          ███    ███ ███   ███   ███    █▄  ███
 *     ███       ███    ███    ▄█    ███     ███            ███          ███    ███ ███   ███   ███    ███ ███▌    ▄
 *    ▄████▀     ██████████  ▄████████▀     ▄████▀         ▄████▀        ███    █▀   ▀█   █▀    ██████████ █████▄▄██
 ******************************************************************************************************************/

package DinoText_GUI.VIEW;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class TestPanelView {
    private JButton jButton_getTime;
    private JTextPane jTextPane_currentTime;
    private JPanel jPanel_testPanel;


    /*************************************
     * ACTION LISTENERS
     ************************************/
    public void addjButton_getTimeListener(ActionListener listenForjButton_getTime) {
        jButton_getTime.addActionListener(listenForjButton_getTime);
    }

    /*************************************
     * GETTER
     ************************************/
    public JPanel getjPanel_testPanel() {
        return jPanel_testPanel;
    }

    /*************************************
     * SET TEXT
     ************************************/
    public void setTextjTextPane_currentTime(String text) {
        jTextPane_currentTime.setText(text);
    }


    /*************************************
     * SET VISIBILITY
     ************************************/
    public void setVisiblejTextPane_currentTime(boolean bool) {
        jTextPane_currentTime.setVisible(bool);
    }

    public void setVisiblejButton_getTime(boolean bool) {
        jButton_getTime.setVisible(bool);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel_testPanel = new JPanel();
        jPanel_testPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        jButton_getTime = new JButton();
        jButton_getTime.setText("Current Time:");
        jPanel_testPanel.add(jButton_getTime, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jTextPane_currentTime = new JTextPane();
        jTextPane_currentTime.setEditable(false);
        jTextPane_currentTime.setText("");
        jPanel_testPanel.add(jTextPane_currentTime, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(300, 200), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel_testPanel;
    }
}
